root: true

extends: airbnb-base

parserOptions:
  sourceType: script

rules:
  max-len:
    - warn
    - code: 88

overrides:
  - files: 'public/**/*.js'
    env:
      browser: true
      jquery: true
      node: false
